# اسم التطبيق
spring.application.name=parking-service

# H2 Database (قاعدة بيانات في الذاكرة)
spring.datasource.url=jdbc:h2:mem:parkingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console (واجهة رسومية لقاعدة البيانات)
spring.h2.console.enabled=true

# Port
server.port=8081